In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Creating tensors

#### Scalar

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int

scalar.item()

7

#### Vector

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

#### MATRIX

In [8]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

#### TENSOR

In [12]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

#### Create a random tensor of size (3,4)

In [16]:
random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.9326, 0.2687, 0.9450, 0.3896],
        [0.2827, 0.2722, 0.0563, 0.4456],
        [0.8235, 0.0276, 0.1917, 0.0292]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

#### Create a random tensor with similar shape to ann image tensor

In [19]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # Colour channel, height, width

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

#### Create a tensor of all zeros

In [20]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#### Create a tensor of all ones

In [21]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Range of tensors and tensors-like

In [23]:
range = torch.arange(start=1, end=11, step=1)

range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Tensors like

In [24]:
ten_zeros = torch.zeros_like(range)

ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data types

In [25]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False) # size/shape, data type, CPU/GPU tensor, gradient tracking 

float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting attributes from tensors

1. datatype - `torch.dtype`
2. shape - `tensor.shape`
3. device - `tensor.device`

In [27]:
some_tensor = torch.rand(3, 4)

some_tensor

tensor([[0.4280, 0.1923, 0.5386, 0.4469],
        [0.7965, 0.9629, 0.8519, 0.6440],
        [0.6441, 0.4372, 0.7024, 0.0940]])

In [28]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication (elements)
* Division
* Matrix multiplication

In [29]:
tensor = torch.tensor([1, 2, 3])

tensor + 10

tensor([11, 12, 13])

In [30]:
tensor - 10

tensor([-9, -8, -7])

In [31]:
tensor * 10

tensor([10, 20, 30])

In [32]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

#### Matrix multiplication

1. Element wise
2. Matrix multiplication (dot-product)

In [33]:
# element wise

tensor * tensor

tensor([1, 4, 9])

In [34]:
# matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

#### Shape errors

In [35]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


In [36]:
tensor_B = tensor_B.T

In [37]:
torch.mm(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor aggregation (min, max, mean, sum, etc.)

In [38]:
x = torch.arange(0, 100, 10)

In [39]:
#torch.min(x), torch.max(x)

x.min(), x.max()

(tensor(0), tensor(90))

In [40]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [41]:
x.sum()

tensor(450)

### Positional min and max

In [42]:
# returns index of the minimum value in the tensor
x.argmin()

tensor(0)

In [43]:
# returns index of the maximmum value in the tensor
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of eachother (vstack) or side by side (hstack)
* Squeeze - removes all single dimensions from a tensor
* Unsqueeze - add `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [44]:
x = torch.arange(1., 10.)

x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
# Add extra dimension

x_reshaped = x.reshape(1, 9)

x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
# Change the view
z = x.view(1, 9)

z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# Changing z changes x since they share the same memory
z[:, 0] = 5

z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [48]:
# Stack tensors on top of eachother | vstack -> dim=0

x_stacked = torch.stack([x, x, x, x], dim=0)

x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [49]:
# Squeeze

x_squeeze = torch.squeeze(x, 0)

x_squeeze, x_squeeze.shape, x_reshaped.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 torch.Size([1, 9]))

In [50]:
# Unsqueeze

x_unsqueeze = torch.unsqueeze(x_squeeze, dim=0)

x_unsqueeze, x_unsqueeze.shape, x_squeeze.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 torch.Size([9]))

In [51]:
# Permute - rearrange the dimensions
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1) # Using the indexes, we rearranged the order of the dimensions

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Indexing

In [52]:
x = torch.arange(1, 10).reshape(1, 3, 3)

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [53]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [55]:
x[0][0][0]

tensor(1)

In [56]:
# Use : to get all of a target dimension

x[:, 0]

tensor([[1, 2, 3]])

In [57]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [58]:
x[:, 0, 0]

tensor([1])

### PyTorch tensors & NumPy

* NumPy -> Tensor = `torch.from_numpy(ndarray)`
* Tensor -> NumPy = `torch.Tensor.numpy()`

In [69]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting, PyTorch reflects NumPy's default datatype of float 64

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [70]:
t_array = tensor.numpy()

t_array

array([1., 2., 3., 4., 5., 6., 7.])

### Reproduceability

In [71]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
